place-clustering-agent:
  build:
    context: place-clustering-agent
    dockerfile: Dockerfile
  image: place-clustering-agent:v1
  container_name: place-clustering-agent
  env_file:
    - .env
  volumes:
    - ./place-clustering-agent/app:/place-clustering-agent/app
  working_dir: /place-clustering-agent/app
  ports:
    - "8001:8000"
  command: ["sleep", "infinity"]
  networks:
    - place_recommender_network